// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiftaokvhwcnqjmovfdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZnRhb2t2aHdjbnFqbW92ZmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDkyMjgsImV4cCI6MjA1OTYyNTIyOH0.uteY6bjJ_RNLxmloH_CgPacHG46sOl3qxZrIA0puo6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);